# Generated by Django 3.2 on 2021-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('pin_code', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
