# Generated by Django 3.2 on 2021-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('pin_code', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('date_of_joining', models.DateField()),
                ('position', models.CharField(max_length=15)),
                ('direct_manager', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=-1)),
                ('email_verified', models.BooleanField()),
                ('all_clear_status', models.BooleanField()),
            ],
        ),
    ]
