# Generated by Django 3.2 on 2021-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
