# Generated by Django 3.2 on 2021-05-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('managed_by', models.CharField(max_length=20)),
                ('date_of_registration', models.DateField()),
                ('pan_number', models.CharField(max_length=11)),
                ('aadhar_number', models.CharField(max_length=20)),
                ('unique_code', models.CharField(default='NOT_ASSIGNED', max_length=15)),
            ],
        ),
    ]
